# Generated by Django 3.2.3 on 2021-06-05 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210604_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_candidate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_recruiter',
        ),
    ]
