# Generated by Django 3.2.3 on 2021-06-03 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('salary_range', models.CharField(choices=[('FR', 'Até 1.000'), ('JR', 'De 1.000 a 2.000'), ('PL', 'De 2.000 a 3.000'), ('SR', 'Acima de 3.000')], max_length=2)),
                ('requirements', models.TextField()),
                ('compulsory_school', models.CharField(choices=[('ELEMENTARY', 'Ensino fundamental'), ('HIGH', 'Ensino médio'), ('TECHNOLOGIST', 'Tecnólogo'), ('COLLEGE', 'Ensino Superior'), ('MASTER', 'Pós / MBA / Mestrado'), ('DOCTORATE', 'Doutorado')], max_length=255)),
                ('recruiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
