# Generated by Django 3.2.3 on 2021-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Vaga', max_length=255, verbose_name='Nome da Vaga'),
        ),
        migrations.AlterField(
            model_name='job',
            name='compulsory_school',
            field=models.CharField(choices=[('ELEMENTARY', 'Ensino fundamental'), ('HIGH', 'Ensino médio'), ('TECHNOLOGIST', 'Tecnólogo'), ('COLLEGE', 'Ensino Superior'), ('MASTER', 'Pós / MBA / Mestrado'), ('DOCTORATE', 'Doutorado')], max_length=255, verbose_name='Escolaridade Mínima'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_range',
            field=models.CharField(choices=[('FR', 'Até 1.000'), ('JR', 'De 1.000 a 2.000'), ('PL', 'De 2.000 a 3.000'), ('SR', 'Acima de 3.000')], max_length=2, verbose_name='Faixa Salarial'),
        ),
    ]
