# Generated by Django 3.2.3 on 2021-06-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_auto_20210603_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='Título', max_length=255, verbose_name='Nome da Vaga'),
        ),
    ]
