# Generated by Django 3.2.3 on 2021-06-04 17:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0010_auto_20210604_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='job', unique=True),
        ),
    ]
